### ISSUE TITLE
Attach tagList id to input element?

### ISSUE THREAD

**Issue by willemx** [timothyarmes/tag-list#1]
Could you also attach the provided tagList id as a html id to the enclosed input element ?
That would make it easier to use the taglist with typeahead.
I could then just do:

```
 Meteor.typeahead(this.find('#id input', ...);
```

Now, I have to enclose the tagList in an extra div with an id if there are more input elements on the page.
...or maybe you know a better way?

**Comment by timothyarmes** [comment]
Good idea. I've made the change.

**Comment by timothyarmes** [comment]
Change pushed.

**Comment by willemx** [comment]
that was fast... thanks!
